In [6]:
import pandas as pd
df_tree = pd.read_csv("../outputs/trajectories_tree_branches_2.csv") # adjust filename
df_tree

,query_id,query,new_query,action_name,query_length,score_spread,score_entropy,step,rank_overlap,query_drift,...,ndcg_after,recall_before,recall_after,cost,latency_ms,cumulative_cost,cumulative_latency_ms,reward,terminal,timeout
0,262156,how long is a college hockey game,how long is a college hockey game period,PseudoRelevanceFeedback,7.0,2.377273,1.912730,1,0.782609,0.055460,...,0.630930,1.0,1.0,0.3,1207.498550,0.3,1207.498550,-0.100250,0,0
1,262156,how long is a college hockey game,A college hockey game period is 20 minutes long.,QueryReform,8.0,0.007487,3.911995,2,0.538462,0.110283,...,0.500000,1.0,1.0,1.0,945.491314,1.3,2152.989864,-0.493376,0,0
2,262156,how long is a college hockey game,A college hockey game period is 20 minutes long.,Rerank,9.0,3.759582,0.927368,3,1.000000,0.110283,...,1.000000,1.0,1.0,0.3,465.948105,1.6,2618.937969,0.924468,0,1
3,262156,how long is a college hockey game,A college hockey game typically lasts about 2 ...,QueryReform,7.0,2.377273,1.912730,1,0.333333,0.112664,...,0.244651,1.0,1.0,1.0,1750.943899,1.0,1750.943899,-1.030923,0,0
4,262156,how long is a college hockey game,A college hockey game typically lasts about 2 ...,Rerank,18.0,6.974228,0.000288,2,1.000000,0.112664,...,0.630930,1.0,1.0,0.3,456.393719,1.3,2207.337618,0.697345,0,0
5,262156,how long is a college hockey game,A college hockey game typically lasts about 2 ...,STOP,18.0,3.924066,1.575037,3,1.000000,0.112664,...,0.630930,1.0,1.0,0.0,0.000000,1.3,2207.337618,0.000000,1,0
6,262156,how long is a college hockey game,how long is a college hockey game,Rerank,7.0,2.377273,1.912730,1,1.000000,0.000000,...,1.000000,1.0,1.0,0.3,579.602480,0.3,579.602480,0.658820,0,0
7,262156,how long is a college hockey game,how long is a college hockey game,STOP,7.0,2.701485,2.292143,2,1.000000,0.000000,...,1.000000,1.0,1.0,0.0,0.000000,0.3,579.602480,0.000000,1,0
8,262156,how long is a college hockey game,how long is a college hockey game,STOP,7.0,2.377273,1.912730,1,1.000000,0.000000,...,0.630930,1.0,1.0,0.0,0.053100,0.0,0.053100,0.000000,1,0
9,1048579,what is pcnt,what is pcnt mla,PseudoRelevanceFeedback,3.0,4.666990,1.258595,1,1.000000,0.248377,...,0.630930,1.0,1.0,0.3,1142.045498,0.3,1142.045498,-0.836209,0,0
10,1048579,what is pcnt,What is PCNT MLA?,QueryReform,4.0,0.004200,3.912014,2,1.000000,0.355238,...,0.630930,1.0,1.0,1.0,733.006001,1.3,1875.051498,-0.224434,0,0
11,1048579,what is pcnt,What is PCNT MLA? viewed,PseudoRelevanceFeedback,4.0,5.980851,1.369063,3,0.722222,0.378288,...,1.000000,1.0,1.0,0.3,1334.514141,1.6,3209.565639,0.633657,0,1
12,1048579,what is pcnt,What is PCNT (Pericentrin)?,QueryReform,3.0,4.666990,1.258595,1,0.866667,0.294901,...,1.000000,1.0,1.0,1.0,1617.609024,1.0,1617.609024,-0.253920,0,0
13,1048579,what is pcnt,What is PCNT (Pericentrin)?,STOP,4.0,10.180398,0.352796,2,1.000000,0.294901,...,1.000000,1.0,1.0,0.0,0.000000,1.0,1617.609024,0.000000,1,0
14,1048579,what is pcnt,what is pcnt,Rerank,3.0,4.666990,1.258595,1,1.000000,0.000000,...,1.000000,1.0,1.0,0.3,379.579544,0.3,379.579544,-0.072653,0,0
15,1048579,what is pcnt,what is pcnt,STOP,3.0,3.649193,2.484641,2,1.000000,0.000000,...,1.000000,1.0,1.0,0.0,0.000000,0.3,379.579544,0.000000,1,0
16,1048579,what is pcnt,what is pcnt,STOP,3.0,4.666990,1.258595,1,1.000000,0.000000,...,1.000000,1.0,1.0,0.0,0.049900,0.0,0.049900,0.000000,1,0

In [ ]:
import pandas as pd
df_rerank = pd.read_csv("../outputs/trajectories_rerank_test_queries_5.csv")      # adjust filename
df_rerank

In [7]:
import pandas as pd
df_random = pd.read_csv("../outputs/trajectories_random_5k.csv")      # adjust filename
df_random.tail(10)

,query_id,query,step,state,action,reward,terminal,timeout
10353,612212,what county is sabula iowa,2,"[5.0, 0.017071129754185677, 0.0541469976305961...",3,0.000000,1,0
10354,153763,distance from zimbabwe to tanzania,0,"[5.0, -0.038696687668561935, 0.062422979623079...",0,-0.223604,0,0
10355,153763,distance from zimbabwe to tanzania,1,"[5.0, -0.038696687668561935, 0.062422979623079...",2,-0.136465,0,0
10356,153763,distance from zimbabwe to tanzania,2,"[5.0, -0.038696687668561935, 0.062422979623079...",1,0.859535,0,1
10357,722250,what is bank charter,0,"[4.0, 0.060952670872211456, -0.025857204571366...",3,0.000000,1,0
10358,995447,definition of anemia by age,0,"[5.0, -0.0018019720446318388, 0.05606841668486...",0,-0.244260,0,0
10359,995447,definition of anemia by age,1,"[5.0, -0.0018019720446318388, 0.05606841668486...",2,-0.117115,0,0
10360,995447,definition of anemia by age,2,"[5.0, -0.0018019720446318388, 0.05606841668486...",2,-0.115326,0,1
10361,1096816,how many people go to a concert,0,"[7.0, 0.13465912640094757, -0.0885564386844635...",1,0.994617,0,0
10362,1096816,how many people go to a concert,1,"[7.0, 0.13465912640094757, -0.0885564386844635...",3,0.000000,1,0

In [10]:
from pathlib import Path

from d3rlpy.dataset import InfiniteBuffer, ReplayBuffer


EXPERT_DATASET_PATH = Path("../outputs/mdp_dataset_trajectories_expert_5k.h5")
RANDOM_DATASET_PATH = Path("../outputs/mdp_dataset_trajectories_random_5k.h5")
TWO_POLICIES_DATASET_PATH = Path("../outputs/mdp_dataset_trajectories_two_policies_5k.h5")

mdp_dataset_expert = ReplayBuffer.load(EXPERT_DATASET_PATH.open("rb"), InfiniteBuffer())
mdp_dataset_random = ReplayBuffer.load(RANDOM_DATASET_PATH.open("rb"), InfiniteBuffer())
for episode in mdp_dataset_random.episodes:
       mdp_dataset_expert.append_episode(episode)
       print(f"Merged episodes: {mdp_dataset_expert.size()}")

    # Do not overwrite either source dataset.
with TWO_POLICIES_DATASET_PATH.open("w+b") as f:
    mdp_dataset_expert.dump(f)

2026-07-21 17:47.51 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]) observation_signature=Signature(dtype=[dtype('float32')], shape=[(399,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)])
2026-07-21 17:47.51 [info     ] Action-space has been automatically determined. action_space=<ActionSpace.DISCRETE: 2>
2026-07-21 17:47.51 [info     ] Action size has been automatically determined. action_size=4
2026-07-21 17:47.55 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]) observation_signature=Signature(dtype=[dtype('float32')], shape=[(399,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)])
2026-07-21 17:47.55 [info     ] Action-space has been automatically determined. action_space=<ActionSpace.DISCRETE: 2>
2026-07-21 17:47.55 [info     ] Action size has been automatically determined. action_size=4
Merged episodes: 5001
Merged episodes: 5002
Merged episodes: 5003
Merged episodes: 5004
Merged episodes: 5005
Merged episodes: 5006
Merged episodes: 5007
Merged episodes: 5008
Merged episodes: 5009
Merged episodes: 5010
Merged episodes: 5011
Merged episodes: 5012
Merged episodes: 5013
Merged episodes: 5014
Merged episodes: 5015
Merged episodes: 5016
Merged episodes: 5017
Merged episodes: 5018
Merged episodes: 5019
Merged episodes: 5020
Merged episodes: 5021
Merged episodes: 5022
Merged episodes: 5023
Merged episodes: 5024
Merged episodes: 5025
Merged episodes: 5026
Merged episodes: 5027
Merged episodes: 5028
Merged episodes: 5029
Merged episodes: 5030
Merged episodes: 5031
Merged episodes: 5032
Merged episodes: 5033
Merged episodes: 5034
Merged episodes: 5035
Merged episodes: 5036
Merged episodes: 5037
Merged episodes: 5038
Merged episodes: 5039
Merged episodes: 5040
Merged episodes: 5041
Merged episodes: 5042
Merged episodes: 5043
Merged episodes: 5044
Merged episodes: 5045
Merged episodes: 5046
Merged episodes: 5047
Merged episodes: 5048
Merged episodes: 5049
Merged episodes: 5050
Merged episodes: 5051
Merged episodes: 5052
Merged episodes: 5053
Merged episodes: 5054
Merged episodes: 5055
Merged episodes: 5056
Merged episodes: 5057
Merged episodes: 5058
Merged episodes: 5059
Merged episodes: 5060
Merged episodes: 5061
Merged episodes: 5062
Merged episodes: 5063
Merged episodes: 5064
Merged episodes: 5065
Merged episodes: 5066
Merged episodes: 5067
Merged episodes: 5068
Merged episodes: 5069
Merged episodes: 5070
Merged episodes: 5071
Merged episodes: 5072
Merged episodes: 5073
Merged episodes: 5074
Merged episodes: 5075
Merged episodes: 5076
Merged episodes: 5077
Merged episodes: 5078
Merged episodes: 5079
Merged episodes: 5080
Merged episodes: 5081
Merged episodes: 5082
Merged episodes: 5083
Merged episodes: 5084
Merged episodes: 5085
Merged episodes: 5086
Merged episodes: 5087
Merged episodes: 5088
Merged episodes: 5089
Merged episodes: 5090
Merged episodes: 5091
Merged episodes: 5092
Merged episodes: 5093
Merged episodes: 5094
Merged episodes: 5095
Merged episodes: 5096
Merged episodes: 5097
Merged episodes: 5098
Merged episodes: 5099
Merged episodes: 5100
Merged episodes: 5101
Merged episodes: 5102
Merged episodes: 5103
Merged episodes: 5104
Merged episodes: 5105
Merged episodes: 5106
Merged episodes: 5107
Merged episodes: 5108
Merged episodes: 5109
Merged episodes: 5110
Merged episodes: 5111
Merged episodes: 5112
Merged episodes: 5113
Merged episodes: 5114
Merged episodes: 5115
Merged episodes: 5116
Merged episodes: 5117
Merged episodes: 5118
Merged episodes: 5119
Merged episodes: 5120
Merged episodes: 5121
Merged episodes: 5122
Merged episodes: 5123
Merged episodes: 5124
Merged episodes: 5125
Merged episodes: 5126
Merged episodes: 5127
Merged episodes: 5128
Merged episodes: 5129
Merged episodes: 5130
Merged episodes: 5131
Merged episodes: 5132
Merged episodes: 5133
Merged episodes: 5134
Merged episodes: 5135
Merged episodes: 5136
Merged episodes: 5137
Merged episodes: 5138
Merged episodes: 5139
Merged episodes: 5140
Merged episodes: 5141
Merged episodes: 5142
Merged episodes: 5143
Merged episodes: 5144
Merged episodes: 5145
Merged episodes: 5146
Merged episodes: 5147
Merged episodes: 5148
Merged episodes: 5149
Merged episodes: 5150
Merged episodes: 5151
Merged episodes: 5152
Merged episodes: 5153
Merged episodes: 5154
Merged episodes: 5155
Merged episodes: 5156
Merged episodes: 5157
Merged episodes: 5158
Merged episodes: 5159
Merged episodes: 5160
Merged episodes: 5161
Merged episodes: 5162
Merged episodes: 5163
Merged episodes: 5164
Merged episodes: 5165
Merged episodes: 5166
Merged episodes: 5167
Merged episodes: 5168
Merged episodes: 5169
Merged episodes: 5170
Merged episodes: 5171
Merged episodes: 5172
Merged episodes: 5173
Merged episodes: 5174
Merged episodes: 5175
Merged episodes: 5176
Merged episodes: 5177
Merged episodes: 5178
Merged episodes: 5179
Merged episodes: 5180
Merged episodes: 5181
Merged episodes: 5182
Merged episodes: 5183
Merged episodes: 5184
Merged episodes: 5185
Merged episodes: 5186
Merged episodes: 5187
Merged episodes: 5188
Merged episodes: 5189
Merged episodes: 5190
Merged episodes: 5191
Merged episodes: 5192
Merged episodes: 5193
Merged episodes: 5194
Merged episodes: 5195
Merged episodes: 5196
Merged episodes: 5197
Merged episodes: 5198
Merged episodes: 5199
Merged episodes: 5200
Merged episodes: 5201
Merged episodes: 5202
Merged episodes: 5203
Merged episodes: 5204
Merged episodes: 5205
Merged episodes: 5206
Merged episodes: 5207
Merged episodes: 5208
Merged episodes: 5209
Merged episodes: 5210
Merged episodes: 5211
Merged episodes: 5212
Merged episodes: 5213
Merged episodes: 5214
Merged episodes: 5215
Merged episodes: 5216
Merged episodes: 5217
Merged episodes: 5218
Merged episodes: 5219
Merged episodes: 5220
Merged episodes: 5221
Merged episodes: 5222
Merged episodes: 5223
Merged episodes: 5224
Merged episodes: 5225
Merged episodes: 5226
Merged episodes: 5227
Merged episodes: 5228
Merged episodes: 5229
Merged episodes: 5230
Merged episodes: 5231
Merged episodes: 5232
Merged episodes: 5233
Merged episodes: 5234
Merged episodes: 5235
Merged episodes: 5236
Merged episodes: 5237
Merged episodes: 5238
Merged episodes: 5239
Merged episodes: 5240
Merged episodes: 5241
Merged episodes: 5242
Merged episodes: 5243
Merged episodes: 5244
Merged episodes: 5245
Merged episodes: 5246
Merged episodes: 5247
Merged episodes: 5248
Merged episodes: 5249
Merged episodes: 5250
Merged episodes: 5251
Merged episodes: 5252
Merged episodes: 5253
Merged episodes: 5254
Merged episodes: 5255
Merged episodes: 5256
Merged episodes: 5257
Merged episodes: 5258
Merged episodes: 5259
Merged episodes: 5260
Merged episodes: 5261
Merged episodes: 5262
Merged episodes: 5263
Merged episodes: 5264
Merged episodes: 5265
Merged episodes: 5266
Merged episodes: 5267
Merged episodes: 5268
Merged episodes: 5269
Merged episodes: 5270
Merged episodes: 5271
Merged episodes: 5272
Merged episodes: 5273
Merged episodes: 5274
Merged episodes: 5275
Merged episodes: 5276
Merged episodes: 5277
Merged episodes: 5278
Merged episodes: 5279
Merged episodes: 5280
Merged episodes: 5281
Merged episodes: 5282
Merged episodes: 5283
Merged episodes: 5284
Merged episodes: 5285
Merged episodes: 5286
Merged episodes: 5287
Merged episodes: 5288
Merged episodes: 5289
Merged episodes: 5290
Merged episodes: 5291
Merged episodes: 5292
Merged episodes: 5293
Merged episodes: 5294
Merged episodes: 5295
Merged episodes: 5296
Merged episodes: 5297
Merged episodes: 5298
Merged episodes: 5299
Merged episodes: 5300
Merged episodes: 5301
Merged episodes: 5302
Merged episodes: 5303
Merged episodes: 5304
Merged episodes: 5305
Merged episodes: 5306
Merged episodes: 5307
Merged episodes: 5308
Merged episodes: 5309
Merged episodes: 5310
Merged episodes: 5311
Merged episodes: 5312
Merged episodes: 5313
Merged episodes: 5314
Merged episodes: 5315
Merged episodes: 5316
Merged episodes: 5317
Merged episodes: 5318
Merged episodes: 5319
Merged episodes: 5320
Merged episodes: 5321
Merged episodes: 5322
Merged episodes: 5323
Merged episodes: 5324
Merged episodes: 5325
Merged episodes: 5326
Merged episodes: 5327
Merged episodes: 5328
Merged episodes: 5329
Merged episodes: 5330
Merged episodes: 5331
Merged episodes: 5332
Merged episodes: 5333
Merged episodes: 5334
Merged episodes: 5335
Merged episodes: 5336
Merged episodes: 5337
Merged episodes: 5338
Merged episodes: 5339
Merged episodes: 5340
Merged episodes: 5341
Merged episodes: 5342
Merged episodes: 5343
Merged episodes: 5344
Merged episodes: 5345
Merged episodes: 5346
Merged episodes: 5347
Merged episodes: 5348
Merged episodes: 5349
Merged episodes: 5350
Merged episodes: 5351
Merged episodes: 5352
Merged episodes: 5353
Merged episodes: 5354
Merged episodes: 5355
Merged episodes: 5356
Merged episodes: 5357
Merged episodes: 5358
Merged episodes: 5359
Merged episodes: 5360
Merged episodes: 5361
Merged episodes: 5362
Merged episodes: 5363
Merged episodes: 5364
Merged episodes: 5365
Merged episodes: 5366
Merged episodes: 5367
Merged episodes: 5368
Merged episodes: 5369
Merged episodes: 5370
Merged episodes: 5371
Merged episodes: 5372
Merged episodes: 5373
Merged episodes: 5374
Merged episodes: 5375
Merged episodes: 5376
Merged episodes: 5377
Merged episodes: 5378
Merged episodes: 5379
Merged episodes: 5380
Merged episodes: 5381
Merged episodes: 5382
Merged episodes: 5383
Merged episodes: 5384
Merged episodes: 5385
Merged episodes: 5386
Merged episodes: 5387
Merged episodes: 5388
Merged episodes: 5389
Merged episodes: 5390
Merged episodes: 5391
Merged episodes: 5392
Merged episodes: 5393
Merged episodes: 5394
Merged episodes: 5395
Merged episodes: 5396
Merged episodes: 5397
Merged episodes: 5398
Merged episodes: 5399
Merged episodes: 5400
Merged episodes: 5401
Merged episodes: 5402
Merged episodes: 5403
Merged episodes: 5404
Merged episodes: 5405
Merged episodes: 5406
Merged episodes: 5407
Merged episodes: 5408
Merged episodes: 5409
Merged episodes: 5410
Merged episodes: 5411
Merged episodes: 5412
Merged episodes: 5413
Merged episodes: 5414
Merged episodes: 5415
Merged episodes: 5416
Merged episodes: 5417
Merged episodes: 5418
Merged episodes: 5419
Merged episodes: 5420
Merged episodes: 5421
Merged episodes: 5422
Merged episodes: 5423
Merged episodes: 5424
Merged episodes: 5425
Merged episodes: 5426
Merged episodes: 5427
Merged episodes: 5428
Merged episodes: 5429
Merged episodes: 5430
Merged episodes: 5431
Merged episodes: 5432
Merged episodes: 5433
Merged episodes: 5434
Merged episodes: 5435
Merged episodes: 5436
Merged episodes: 5437
Merged episodes: 5438
Merged episodes: 5439
Merged episodes: 5440
Merged episodes: 5441
Merged episodes: 5442
Merged episodes: 5443
Merged episodes: 5444
Merged episodes: 5445
Merged episodes: 5446
Merged episodes: 5447
Merged episodes: 5448
Merged episodes: 5449
Merged episodes: 5450
Merged episodes: 5451
Merged episodes: 5452
Merged episodes: 5453
Merged episodes: 5454
Merged episodes: 5455
Merged episodes: 5456
Merged episodes: 5457
Merged episodes: 5458
Merged episodes: 5459
Merged episodes: 5460
Merged episodes: 5461
Merged episodes: 5462
Merged episodes: 5463
Merged episodes: 5464
Merged episodes: 5465
Merged episodes: 5466
Merged episodes: 5467
Merged episodes: 5468
Merged episodes: 5469
Merged episodes: 5470
Merged episodes: 5471
Merged episodes: 5472
Merged episodes: 5473
Merged episodes: 5474
Merged episodes: 5475
Merged episodes: 5476
Merged episodes: 5477
Merged episodes: 5478
Merged episodes: 5479
Merged episodes: 5480
Merged episodes: 5481
Merged episodes: 5482
Merged episodes: 5483
Merged episodes: 5484
Merged episodes: 5485
Merged episodes: 5486
Merged episodes: 5487
Merged episodes: 5488
Merged episodes: 5489
Merged episodes: 5490
Merged episodes: 5491
Merged episodes: 5492
Merged episodes: 5493
Merged episodes: 5494
Merged episodes: 5495
Merged episodes: 5496
Merged episodes: 5497
Merged episodes: 5498
Merged episodes: 5499
Merged episodes: 5500
Merged episodes: 5501
Merged episodes: 5502
Merged episodes: 5503
Merged episodes: 5504
Merged episodes: 5505
Merged episodes: 5506
Merged episodes: 5507
Merged episodes: 5508
Merged episodes: 5509
Merged episodes: 5510
Merged episodes: 5511
Merged episodes: 5512
Merged episodes: 5513
Merged episodes: 5514
Merged episodes: 5515
Merged episodes: 5516
Merged episodes: 5517
Merged episodes: 5518
Merged episodes: 5519
Merged episodes: 5520
Merged episodes: 5521
Merged episodes: 5522
Merged episodes: 5523
Merged episodes: 5524
Merged episodes: 5525
Merged episodes: 5526
Merged episodes: 5527
Merged episodes: 5528
Merged episodes: 5529
Merged episodes: 5530
Merged episodes: 5531
Merged episodes: 5532
Merged episodes: 5533
Merged episodes: 5534
Merged episodes: 5535
Merged episodes: 5536
Merged episodes: 5537
Merged episodes: 5538
Merged episodes: 5539
Merged episodes: 5540
Merged episodes: 5541
Merged episodes: 5542
Merged episodes: 5543
Merged episodes: 5544
Merged episodes: 5545
Merged episodes: 5546
Merged episodes: 5547
Merged episodes: 5548
Merged episodes: 5549
Merged episodes: 5550
Merged episodes: 5551
Merged episodes: 5552
Merged episodes: 5553
Merged episodes: 5554
Merged episodes: 5555
Merged episodes: 5556
Merged episodes: 5557
Merged episodes: 5558
Merged episodes: 5559
Merged episodes: 5560
Merged episodes: 5561
Merged episodes: 5562
Merged episodes: 5563
Merged episodes: 5564
Merged episodes: 5565
Merged episodes: 5566
Merged episodes: 5567
Merged episodes: 5568
Merged episodes: 5569
Merged episodes: 5570
Merged episodes: 5571
Merged episodes: 5572
Merged episodes: 5573
Merged episodes: 5574
Merged episodes: 5575
Merged episodes: 5576
Merged episodes: 5577
Merged episodes: 5578
Merged episodes: 5579
Merged episodes: 5580
Merged episodes: 5581
Merged episodes: 5582
Merged episodes: 5583
Merged episodes: 5584
Merged episodes: 5585
Merged episodes: 5586
Merged episodes: 5587
Merged episodes: 5588
Merged episodes: 5589
Merged episodes: 5590
Merged episodes: 5591
Merged episodes: 5592
Merged episodes: 5593
Merged episodes: 5594
Merged episodes: 5595
Merged episodes: 5596
Merged episodes: 5597
Merged episodes: 5598
Merged episodes: 5599
Merged episodes: 5600
Merged episodes: 5601
Merged episodes: 5602
Merged episodes: 5603
Merged episodes: 5604
Merged episodes: 5605
Merged episodes: 5606
Merged episodes: 5607
Merged episodes: 5608
Merged episodes: 5609
Merged episodes: 5610
Merged episodes: 5611
Merged episodes: 5612
Merged episodes: 5613
Merged episodes: 5614
Merged episodes: 5615
Merged episodes: 5616
Merged episodes: 5617
Merged episodes: 5618
Merged episodes: 5619
Merged episodes: 5620
Merged episodes: 5621
Merged episodes: 5622
Merged episodes: 5623
Merged episodes: 5624
Merged episodes: 5625
Merged episodes: 5626
Merged episodes: 5627
Merged episodes: 5628
Merged episodes: 5629
Merged episodes: 5630
Merged episodes: 5631
Merged episodes: 5632
Merged episodes: 5633
Merged episodes: 5634
Merged episodes: 5635
Merged episodes: 5636
Merged episodes: 5637
Merged episodes: 5638
Merged episodes: 5639
Merged episodes: 5640
Merged episodes: 5641
Merged episodes: 5642
Merged episodes: 5643
Merged episodes: 5644
Merged episodes: 5645
Merged episodes: 5646
Merged episodes: 5647
Merged episodes: 5648
Merged episodes: 5649
Merged episodes: 5650
Merged episodes: 5651
Merged episodes: 5652
Merged episodes: 5653
Merged episodes: 5654
Merged episodes: 5655
Merged episodes: 5656
Merged episodes: 5657
Merged episodes: 5658
Merged episodes: 5659
Merged episodes: 5660
Merged episodes: 5661
Merged episodes: 5662
Merged episodes: 5663
Merged episodes: 5664
Merged episodes: 5665
Merged episodes: 5666
Merged episodes: 5667
Merged episodes: 5668
Merged episodes: 5669
Merged episodes: 5670
Merged episodes: 5671
Merged episodes: 5672
Merged episodes: 5673
Merged episodes: 5674
Merged episodes: 5675
Merged episodes: 5676
Merged episodes: 5677
Merged episodes: 5678
Merged episodes: 5679
Merged episodes: 5680
Merged episodes: 5681
Merged episodes: 5682
Merged episodes: 5683
Merged episodes: 5684
Merged episodes: 5685
Merged episodes: 5686
Merged episodes: 5687
Merged episodes: 5688
Merged episodes: 5689
Merged episodes: 5690
Merged episodes: 5691
Merged episodes: 5692
Merged episodes: 5693
Merged episodes: 5694
Merged episodes: 5695
Merged episodes: 5696
Merged episodes: 5697
Merged episodes: 5698
Merged episodes: 5699
Merged episodes: 5700
Merged episodes: 5701
Merged episodes: 5702
Merged episodes: 5703
Merged episodes: 5704
Merged episodes: 5705
Merged episodes: 5706
Merged episodes: 5707
Merged episodes: 5708
Merged episodes: 5709
Merged episodes: 5710
Merged episodes: 5711
Merged episodes: 5712
Merged episodes: 5713
Merged episodes: 5714
Merged episodes: 5715
Merged episodes: 5716
Merged episodes: 5717
Merged episodes: 5718
Merged episodes: 5719
Merged episodes: 5720
Merged episodes: 5721
Merged episodes: 5722
Merged episodes: 5723
Merged episodes: 5724
Merged episodes: 5725
Merged episodes: 5726
Merged episodes: 5727
Merged episodes: 5728
Merged episodes: 5729
Merged episodes: 5730
Merged episodes: 5731
Merged episodes: 5732
Merged episodes: 5733
Merged episodes: 5734
Merged episodes: 5735
Merged episodes: 5736
Merged episodes: 5737
Merged episodes: 5738
Merged episodes: 5739
Merged episodes: 5740
Merged episodes: 5741
Merged episodes: 5742
Merged episodes: 5743
Merged episodes: 5744
Merged episodes: 5745
Merged episodes: 5746
Merged episodes: 5747
Merged episodes: 5748
Merged episodes: 5749
Merged episodes: 5750
Merged episodes: 5751
Merged episodes: 5752
Merged episodes: 5753
Merged episodes: 5754
Merged episodes: 5755
Merged episodes: 5756
Merged episodes: 5757
Merged episodes: 5758
Merged episodes: 5759
Merged episodes: 5760
Merged episodes: 5761
Merged episodes: 5762
Merged episodes: 5763
Merged episodes: 5764
Merged episodes: 5765
Merged episodes: 5766
Merged episodes: 5767
Merged episodes: 5768
Merged episodes: 5769
Merged episodes: 5770
Merged episodes: 5771
Merged episodes: 5772
Merged episodes: 5773
Merged episodes: 5774
Merged episodes: 5775
Merged episodes: 5776
Merged episodes: 5777
Merged episodes: 5778
Merged episodes: 5779
Merged episodes: 5780
Merged episodes: 5781
Merged episodes: 5782
Merged episodes: 5783
Merged episodes: 5784
Merged episodes: 5785
Merged episodes: 5786
Merged episodes: 5787
Merged episodes: 5788
Merged episodes: 5789
Merged episodes: 5790
Merged episodes: 5791
Merged episodes: 5792
Merged episodes: 5793
Merged episodes: 5794
Merged episodes: 5795
Merged episodes: 5796
Merged episodes: 5797
Merged episodes: 5798
Merged episodes: 5799
Merged episodes: 5800
Merged episodes: 5801
Merged episodes: 5802
Merged episodes: 5803
Merged episodes: 5804
Merged episodes: 5805
Merged episodes: 5806
Merged episodes: 5807
Merged episodes: 5808
Merged episodes: 5809
Merged episodes: 5810
Merged episodes: 5811
Merged episodes: 5812
Merged episodes: 5813
Merged episodes: 5814
Merged episodes: 5815
Merged episodes: 5816
Merged episodes: 5817
Merged episodes: 5818
Merged episodes: 5819
Merged episodes: 5820
Merged episodes: 5821
Merged episodes: 5822
Merged episodes: 5823
Merged episodes: 5824
Merged episodes: 5825
Merged episodes: 5826
Merged episodes: 5827
Merged episodes: 5828
Merged episodes: 5829
Merged episodes: 5830
Merged episodes: 5831
Merged episodes: 5832
Merged episodes: 5833
Merged episodes: 5834
Merged episodes: 5835
Merged episodes: 5836
Merged episodes: 5837
Merged episodes: 5838
Merged episodes: 5839
Merged episodes: 5840
Merged episodes: 5841
Merged episodes: 5842
Merged episodes: 5843
Merged episodes: 5844
Merged episodes: 5845
Merged episodes: 5846
Merged episodes: 5847
Merged episodes: 5848
Merged episodes: 5849
Merged episodes: 5850
Merged episodes: 5851
Merged episodes: 5852
Merged episodes: 5853
Merged episodes: 5854
Merged episodes: 5855
Merged episodes: 5856
Merged episodes: 5857
Merged episodes: 5858
Merged episodes: 5859
Merged episodes: 5860
Merged episodes: 5861
Merged episodes: 5862
Merged episodes: 5863

In [5]:
import pandas as pd
df_test_results = pd.read_csv("../outputs/cql_test_results2.csv")      
df_test_results

,query_id,query_text,step,action,action_name,ndcg_before,ndcg_after,delta_ndcg,recall_before,recall_after,delta_recall,action_cost,elapsed_ms,cumulative_cost,reward,terminated,termination_reason
0,1048579,what is pcnt,0,3,STOP,1.000000,1.00000,0.000000,1.0,1.0,0.0,0.0,0.000000,0.0,0.000000,True,policy_stop
1,262156,how long is a college hockey game,0,1,Rerank,0.630930,1.00000,0.369070,1.0,1.0,0.0,0.3,404.932499,0.3,0.664643,False,NaN
2,262156,how long is a college hockey game,1,3,STOP,1.000000,1.00000,0.000000,1.0,1.0,0.0,0.0,0.000000,0.3,0.000000,True,policy_stop
3,1048601,what is pastoral medicine,0,0,QueryReform,0.430677,0.63093,0.200253,1.0,1.0,0.0,1.0,5568.119526,1.0,0.014902,False,NaN
4,1048601,"What is pastoral medicine, including its defin...",1,3,STOP,0.630930,0.63093,0.000000,1.0,1.0,0.0,0.0,0.000000,1.0,0.000000,True,policy_stop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,1051364,who sings love shack baby,0,3,STOP,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,True,policy_stop
82,1051376,what is meant by solution concentration and wh...,0,3,STOP,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,True,policy_stop
83,1051401,what is meant by robust software,0,0,QueryReform,0.000000,0.00000,0.000000,0.0,0.0,0.0,1.0,5882.429123,1.0,-0.396081,False,NaN
84,1051401,What is meant by robust software in the contex...,1,0,QueryReform,0.000000,0.00000,0.000000,0.0,0.0,0.0,1.0,8874.250412,2.0,-0.495808,False,NaN
85,1051401,What is the definition and meaning of robust s...,2,3,STOP,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.000000,2.0,0.000000,True,policy_stop